### ISSUE TITLE
Erreur d'affichage au niveau des apostrophes

### ISSUE THREAD

**Issue by Emeraldfromverdanturf** [WWX-Team/bescherelle#23]
Les apostrophes ne s'affichent pas correctement dans les tableaux de conjugaison 

Ci-joint un exemple

![Erreur affichage apostrophes](https://github.com/WWX-Team/bescherelle/assets/69898597/92be9730-be5e-4211-9efb-6bf350c7deac)

**Comment by wilhelmbismarck** [comment]
Bonsoir - il n'y a pas d'erreur sur ce point là, regarde la fonction `conjuguer_an_trouver_verbe` de `scripts.py` pour en savoir plus.

Les verbes pronominaux ne sont pas encore supportés.
