### ISSUE TITLE
Verbes irréguliers

### ISSUE THREAD

**Issue by wedego943** [WWX-Team/bescherelle#3]
Dans la liste de verbes irréguliers (le screen dans ToDoList), il manque plusieurs verbes (comme 'aller' par exemple).
La question est : est-ce normal ? ou est-ce mal recopié sur mon taff ?

**Comment by wilhelmbismarck** [comment]
je regarde ça

**Comment by wilhelmbismarck** [comment]
il manque effectivement aller, si tu trouves des verbes IRR __**bases**__ (~~accourir~~ > _courir_) tu peux les ajouter à la to do list, en dessous de l'image
