### ISSUE TITLE
deboggage scripts

### ISSUE THREAD

**Issue by wedego943** [WWX-Team/bescherelle#4]
erreur à la fonction 'verbe_analyse_term_brute'  : 
![image](https://github.com/WWX-Team/bescherelle/assets/106106763/871946ec-f5a1-456c-ad35-bfd0d5b59704)

et question aussi : qu'est-ce que    data=" "   ?

**Comment by wilhelmbismarck** [comment]
il faut entrer du contenu
au pire, ajoute : 
```python
if len(verbe) == 0: return data
```

c'est une fonction qui se répète elle-même
(dite à profondeur, c'est un + qu'il y en ait une)
