### ISSUE TITLE
structurer le dico retourné par 'conjuguer' 

### ISSUE THREAD

**Issue by wedego943** [WWX-Team/bescherelle#8]
faut le faire dans la fonction du coup
faudrait faire un truc genre : 
'présent' : [chante,
                 chantes,
                ...]
'futur' : etc

**Comment by wilhelmbismarck** [comment]
C'est déjà le cas
Les données sont organisées, et en plus, retournent des infos complémentaires

**Comment by wilhelmbismarck** [comment]
Regarde la documentation de la fonction conjuguer, la deuxième
